### ISSUE TITLE
REMOVAL logic

### ISSUE THREAD

**Issue by Mothluin** [Thornsnake/MCRBot#6] opened 2021-11-25 20:16 UTC
Hi :)
My bot is configured to trade the top 10 coins (plus other personal favorites).

Recently (2021-11-21T11:45:07) AVAX made it to the top 10 list and the bot rebalanced to buy.
In the past couple of days, however, AVAX fell off the top and anchored at 11th place: despite `REMOVAL` is set to 24 hours in my `config.ts` file, I still see the coin in my portfolio.
Plus the bot is still actively rebalancing it:

`2021-11-25T16:55:18: [BUY] AVAX for 0.722 USDT`

Have you experienced similar issues?

Thanks

**Comment by Thornsnake** [comment] 2021-11-25 20:31
When a coin falls out of the market cap and you've set the removal wait time to 24 hours, then that coin needs to stay out of the top 10 for a full 24 hours. If at any point the coin moves back into the top 10 during that time, the timer is reset to a full 24 hours.

If you want to check when the bot has scheduled the coin for removal, check the `./data/CoinRemovalList.json` file. You will find the `execute` attribute for all coins that are scheduled for removal. That attribute is the number of milliseconds since 1970-01-01 (Unix Epoch Time). That is the time the bot will remove the coin at.

If you want to convert that number into a human readable fomat, you can enter it here: https://www.epochconverter.com/

**Comment by Mothluin** [comment] 2021-11-25 22:21
Thanks
Bit by bit, I'm understanding more about this bot.

I checked the file and the content is as follows:

`[{"coin":"AVAX","execute":1637749211290}]
CoinRemovalList.json (END)`

The epoch time confirms the bot should have sold AVAX as of yesterday :)

**Comment by Thornsnake** [comment] 2021-11-25 22:51
That is indeed strange then. The coin should have been sold already.

The market cap rebalancing happens during the rebalance schedule. You've probably tried this already, but could you attempt to restart the bot (`sh restart.sh`) to make sure nothing is stuck? Is there anything in the logs that would indicate and issue around the time rebalancing happens?

**Comment by Mothluin** [comment] 2021-11-26 12:06
I will restart the bot now and see if it executes sell action scheduled in the past.

That epoch time converts to GMT: Wednesday, November 24, 2021 10:20:11.290 AM.
The log file doesn't report anything suspicious at that time:

```
2021-11-24T10:10:06: [CHECK] Rebalance not necessary
2021-11-24T10:15:05: [CHECK] Rebalance not necessary
2021-11-24T10:20:05: [CHECK] Rebalance not necessary
2021-11-24T10:25:06: [CHECK] Rebalance not necessary
2021-11-24T10:30:08: [CHECK] Rebalance not necessary
2021-11-24T10:35:05: [CHECK] Rebalance not necessary
2021-11-24T10:40:07: [CHECK] Rebalance not necessary
2021-11-24T10:45:07: [CHECK] Rebalance not necessary
2021-11-24T10:50:05: [CHECK] Rebalance not necessary
2021-11-24T10:55:05: [CHECK] Rebalance not necessary
2021-11-24T11:00:27: [CHECK] Rebalance not necessary
2021-11-24T11:05:07: [CHECK] Rebalance not necessary
2021-11-24T11:10:06: [CHECK] Rebalance not necessary
2021-11-24T11:15:04: [CHECK] Rebalance not necessary
2021-11-24T11:20:05: [CHECK] Rebalance not necessary
2021-11-24T11:25:06: [CHECK] Rebalance not necessary
2021-11-24T11:30:05: [CHECK] Rebalance not necessary
```


Timeout errors are way beyond the scheduled time:

```
2021-11-24T14:50:34: Error - timeout of 30000ms exceeded
2021-11-24T15:20:30: Error - timeout of 30000ms exceeded
2021-11-24T15:45:34: Error - timeout of 30000ms exceeded
2021-11-24T16:00:30: Error - timeout of 30000ms exceeded
2021-11-24T17:05:30: Error - timeout of 30000ms exceeded
2021-11-24T18:15:32: Error - timeout of 30000ms exceeded
2021-11-24T18:45:30: Error - timeout of 30000ms exceeded
2021-11-24T19:55:31: Error - timeout of 30000ms exceeded
2021-11-24T20:55:30: Error - timeout of 30000ms exceeded
2021-11-24T22:00:31: Error - timeout of 30000ms exceeded
```

**Comment by Thornsnake** [comment] 2021-11-29 21:24
Really sorry for the late answer. I have been a bit busy the last few days.

Having learned the best customer support techniques from the ones I'm using, I'd first like to ask if the problem still exists. =)

**Comment by Mothluin** [comment] 2021-11-30 22:27
Nevermind 😊

I can confirm AVAX is still part of my portfolio.
Didn't edit the CoinRemovalList.jsn but also didn't restart the bot yet:
would like AVAX to push a little bit more in the green zone before taking
any action, just in case a restart is all it's required to trigger the sell
😝

Will report back soon, hopefully!

**Comment by Mothluin** [comment] 2021-12-08 17:25
I'm now also monitoring what happens to LUNA, since this coin also made it to the top 10.
Am I free to edit/move/delete the `CoinRemovalList.json` file in a similar way you instructed for the `PortfolioATH.json` file?

I might try to alter the epoch timestamp for the `execute` parameter - in order to grant a "second wind" - and record if the bot eventually sells AVAX.

**Comment by Mothluin** [comment] 2021-12-15 14:07
`CoinRemovalList.json` now includes LUNA:

```
[{"coin":"AVAX","execute":1638707702660},{"coin":"LUNA","execute":1639565702102}]
(END)
```

The converted epoch time was 11:55 AM CET.
Still have LUNA in my portfolio.

**Comment by Mothluin** [comment] 2021-12-19 15:00
LUNA and AVAX consolidated their 9th and 10th market cap position recently.
The bot correctly removed the `execute` entries from the `CoinRemovalList.json` file.

However, that happened at the expense of DOT, now in 11th position.
Once again, the bot behaved in a correct way and added an entry in the `CoinRemovalList.json` file:

```
[{"coin":"DOT","execute":1639978501163}]
CoinRemovalList.json (END)
```

The epoch time suggests DOT shall be sold Monday, December 20, 2021 6:35:01.163 AM.
That is, as long as it doesn't make it to the top 10 again.

I will wait and report back if the bot sells as expected.

**Comment by Mothluin** [comment] 2021-12-25 11:38
I can confidently report DOT was not sold.
AVAX also dropped out of the top 10 again, the `CoinRemovalList.json` file got updated:

```
[{"coin":"AVAX","execute":1640350501349}]
CoinRemovalList.json (END)
```

The coin should have been sold Friday, December 24, 2021 1:55:01.349 PM: this didn't happen.
Instead, the bot is still rebalancing on it:

```
[...]
2021-12-25T02:05:04: [CHECK] AVAX deviates -3.4446061092261857 USDT (-5.26%) -> [UNDERPERFORMING]
2021-12-25T02:05:05: [SELL] XLM for 2.899709738773822 USDT
2021-12-25T02:05:05: [SELL] SOL for 2.672186738773817 USDT
2021-12-25T02:05:06: [BUY] AVAX for 3.444 USDT
2021-12-25T02:05:07: [BUY] CRO for 1.97741 USDT
[...]
```

Hope these reports are useful hints to find the issue.

**Comment by Mothluin** [comment] 2021-12-25 11:47
I also just restarted the bot, as you originally suggested, but there's no retro-active selling:

```
2021-12-25T11:35:04: [CHECK] Rebalance not necessary
2021-12-25T11:39:08:
2021-12-25T11:39:08: Received SIGINT signal
2021-12-25T11:39:08: Shutting down
2021-12-25T11:39:08:
2021-12-25T11:39:11: Trailing Stop at [30 * * * * *] with 30% min profit and 20% max drop ...
2021-12-25T11:39:11: Investing at [0 3 0 * * *] with 25 USDT ...
2021-12-25T11:39:11: Rebalancing at [0 */5 * * * *] with threshold of 5% ...
2021-12-25T11:39:11:
2021-12-25T11:40:03: [CHECK] Rebalance not necessary
```

**Comment by Mothluin** [comment] 2022-03-05 07:18
Hi
Any chance you had time to look into this problem?
Thanks

**Comment by VixJB** [comment] 2022-04-18 20:04
I am seeing the same thing coins are going out of top coins and are appearing in the CoinRemovalList but continue to be traded. New coins moving in seem to be added, but coins never actually get removed as far as I can tell.

**Comment by Thornsnake** [comment] 2022-04-19 22:36
I could not reproduce this previously, but it's happening to me too now. Will look into it tomorrow and release a fix.

**Comment by Thornsnake** [comment] 2022-04-20 18:12
This should have been fixed.

Please update the bot with `sh update.sh` and let me know if it's working.
The sell-off should be triggered during the next rebalance cycle, which is by default every full 5 minutes.

**Comment by VixJB** [comment] 2022-04-23 01:45
Yes seems to have fixed the issue I was seeing. The earliest time is now in the future.

**Comment by Thornsnake** [comment] 2022-04-23 08:05
Awesome, closing this issue now.

**Closed as completed by Thornsnake** 2022-04-23 08:05 UTC

**Comment by Mothluin** [comment] 2022-04-23 19:31
Hi
I think I can also confirm this is fixed now.

I'm just wondering if the `REMOVAL` option in `config.ts` is still considered when a coin falls off the top X coins.
And, if before `REMOVAL` time elapses the coin makes it back into the top X coins, I guess the bot will then ignore the scheduled action to sell.

**Comment by Mothluin** [comment] 2022-04-23 19:41
Also: if the coin makes it back to the top X coins after `REMOVAL` elapses, will the bot buy back?

My bot instance sold my AVAX holding earlier today:

`2022-04-23T15:15:01: [CHECK] AVAX should not be in the portfolio`

AVAX is now ranking 10 but no buy back happened yet.
Could it be this happens at the next daily investment?
