### ISSUE TITLE
Bot suddenly bought DAI stablecoin (rank 97) even though its set to track top25 plus extra coins outside of top25

### ISSUE THREAD

**Issue by milllan** [Thornsnake/MCRBot#2] opened 2021-09-28 11:38 UTC
I've added it to exclude list

https://1drv.ms/u/s!Ak_Chc7UYPhq1ccJ7OENgOiIRvq1eg?e=IIe2hI

`2021-09-28T06:16:44: Received SIGINT signal
2021-09-28T06:16:44: Shutting down
2021-09-28T06:16:44: 
2021-09-28T06:16:47: Trailing Stop at [24 * * * * *] with 30% min profit and 20% max drop ...
2021-09-28T06:16:47: Investing at [25 4 14 * * *] with 25 USDT ...
2021-09-28T06:16:47: Rebalancing at [44 */1 */1 * * *] with threshold of 3.9% ...
2021-09-28T06:16:47: 
2021-09-28T10:00:47: [CHECK] KSM deviates 1.061393546107837 USDT (4.27%) -> [OVERPERFORMING]
2021-09-28T10:00:47: [SELL] KSM for 1.061393546107837 USDT
2021-09-28T10:00:48: [BUY] SAND for 0.54703 USDT
2021-09-28T10:00:48: [BUY] ALGO for 0.5143 USDT
2021-09-28T11:20:47: [CHECK] UNI deviates 1.2174973641182447 USDT (4.07%) -> [OVERPERFORMING]
2021-09-28T11:20:47: [SELL] UNI for 1.2174973641182447 USDT
2021-09-28T11:20:48: [BUY] ATOM for 0.599 USDT
2021-09-28T11:20:48: [BUY] LUNA for 0.4757 USDT
2021-09-28T11:20:49: [BUY] CRO for 0.14279 USDT
2021-09-28T12:35:47: [CHECK] MATIC deviates 1.8490299535482713 USDT (6.59%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] UNI deviates 1.9178183335482757 USDT (6.84%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] LUNA deviates 1.3396835535482765 USDT (4.78%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] LINK deviates 2.116735553548274 USDT (7.55%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] DOT deviates 2.106300353548278 USDT (7.51%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] SOL deviates 1.5647125535482793 USDT (5.58%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] BTC deviates 1.6892303535482753 USDT (6.02%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] LTC deviates 2.1503682535482724 USDT (7.67%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] AVAX deviates 1.395690553548274 USDT (4.98%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] ATOM deviates 1.555835553548274 USDT (5.55%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] ETH deviates 1.6312775535482729 USDT (5.82%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] ALGO deviates 1.565443553548274 USDT (5.58%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] ADA deviates 2.100673553548276 USDT (7.49%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] CRO deviates 1.4397676144606315 USDT (5.13%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] EGLD deviates 2.2540675535482784 USDT (8.04%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [CHECK] SAND deviates 1.6201757535482741 USDT (5.78%) -> [OVERPERFORMING]
2021-09-28T12:35:47: [SELL] MATIC for 1.8490299535482713 USDT
2021-09-28T12:35:48: [SELL] UNI for 1.9178183335482757 USDT
2021-09-28T12:35:48: [SELL] LUNA for 1.3396835535482765 USDT
2021-09-28T12:35:49: [SELL] LINK for 2.116735553548274 USDT
2021-09-28T12:35:49: [SELL] DOT for 2.106300353548278 USDT
2021-09-28T12:35:50: [SELL] SOL for 1.5647125535482793 USDT
2021-09-28T12:35:50: [SELL] BTC for 1.6892303535482753 USDT
2021-09-28T12:35:50: [SELL] LTC for 2.1503682535482724 USDT
2021-09-28T12:35:51: [SELL] AVAX for 1.395690553548274 USDT
2021-09-28T12:35:51: [SELL] ATOM for 1.555835553548274 USDT
2021-09-28T12:35:52: [SELL] ETH for 1.6312775535482729 USDT
2021-09-28T12:35:52: [SELL] ALGO for 1.565443553548274 USDT
2021-09-28T12:35:53: [SELL] ADA for 2.100673553548276 USDT
2021-09-28T12:35:53: [SELL] CRO for 1.4397676144606315 USDT
2021-09-28T12:35:54: [SELL] EGLD for 2.2540675535482784 USDT
2021-09-28T12:35:54: [SELL] SAND for 1.6201757535482741 USDT
2021-09-28T12:35:55: [BUY] DAI for 28.0486 USDT
2021-09-28T12:35:55: [BUY] FET for 0.24821 USDT
2021-09-28T13:23:19: 
2021-09-28T13:23:19: Received SIGINT signal
2021-09-28T13:23:19: Shutting down
2021-09-28T13:23:19: 
2021-09-28T13:23:21: Trailing Stop at [24 * * * * *] with 30% min profit and 20% max drop ...
2021-09-28T13:23:21: Investing at [25 4 14 * * *] with 25 USDT ...
2021-09-28T13:23:21: Rebalancing at [44 */1 */1 * * *] with threshold of 3.89% ...
2021-09-28T13:23:21: 
2021-09-28T13:23:46: [CHECK] DAI should not be in the portfolio
2021-09-28T13:23:46: [SELL] DAI for 28.048 USDT
2021-09-28T13:23:47: [BUY] MATIC for 1.33561 USDT
2021-09-28T13:23:48: [BUY] UNI for 1.3356 USDT
2021-09-28T13:23:48: [BUY] LUNA for 1.3356 USDT
2021-09-28T13:23:48: [BUY] LINK for 1.335 USDT
2021-09-28T13:23:49: [BUY] DOT for 1.3356 USDT
2021-09-28T13:23:49: [BUY] SOL for 1.335 USDT
2021-09-28T13:23:50: [BUY] BTC for 1.33 USDT
2021-09-28T13:23:50: [BUY] LTC for 1.33 USDT
2021-09-28T13:23:51: [BUY] AVAX for 1.335 USDT
2021-09-28T13:23:51: [BUY] ATOM for 1.335 USDT
2021-09-28T13:23:52: [BUY] ETH for 1.33 USDT
2021-09-28T13:23:52: [BUY] ALGO for 1.3356 USDT
2021-09-28T13:23:53: [BUY] ADA for 1.33561 USDT
2021-09-28T13:23:53: [BUY] CRO for 1.33561 USDT
2021-09-28T13:23:54: [BUY] CHZ for 1.33561 USDT
2021-09-28T13:23:54: [BUY] EGLD for 1.3356 USDT
2021-09-28T13:23:55: [BUY] ENJ for 1.33561 USDT
2021-09-28T13:23:55: [BUY] FET for 1.33561 USDT
2021-09-28T13:23:55: [BUY] KSM for 1.335 USDT
2021-09-28T13:23:56: [BUY] SAND for 1.33561 USDT
2021-09-28T13:23:56: [BUY] ZIL for 1.33561 USDT
2021-09-28T13:23:57: [CHECK] CHZ deviates 1.358467912556545 USDT (5.38%) -> [OVERPERFORMING]
2021-09-28T13:23:57: [CHECK] ENJ deviates 1.4441008125565489 USDT (5.72%) -> [OVERPERFORMING]
2021-09-28T13:23:57: [CHECK] KSM deviates 1.8198598125565475 USDT (7.21%) -> [OVERPERFORMING]
2021-09-28T13:23:57: [CHECK] ZIL deviates 1.3477858125565447 USDT (5.34%) -> [OVERPERFORMING]
2021-09-28T13:23:58: [SELL] CHZ for 1.358467912556545 USDT
2021-09-28T13:23:58: [SELL] ENJ for 1.4441008125565489 USDT
2021-09-28T13:23:59: [SELL] KSM for 1.8198598125565475 USDT
2021-09-28T13:23:59: [SELL] ZIL for 1.3477858125565447 USDT
2021-09-28T13:24:00: [BUY] CRO for 0.92427 USDT
2021-09-28T13:24:00: [BUY] EGLD for 0.7203 USDT
2021-09-28T13:24:01: [BUY] ATOM for 0.52 USDT
2021-09-28T13:24:01: [BUY] BTC for 0.48 USDT
2021-09-28T13:24:02: [BUY] AVAX for 0.485 USDT
2021-09-28T13:24:02: [BUY] ETH for 0.46 USDT
2021-09-28T13:24:03: [BUY] DOT for 0.4586 USDT
2021-09-28T13:24:03: [BUY] LINK for 0.436 USDT
2021-09-28T13:24:04: [BUY] MATIC for 0.41482 USDT
2021-09-28T13:24:04: [BUY] ADA for 0.40655 USDT
2021-09-28T13:24:04: [BUY] SAND for 0.36291 USDT
2021-09-28T13:24:05: [BUY] SOL for 0.301 USDT
2021-09-28T13:31:46: [CHECK] FET deviates 1.034425283533487 USDT (3.93%) -> [OVERPERFORMING]
2021-09-28T13:31:47: [SELL] FET for 1.034425283533487 USDT
2021-09-28T13:31:48: [BUY] LUNA for 0.3937 USDT
2021-09-28T13:31:48: [BUY] LTC for 0.3 USDT
2021-09-28T13:31:49: [BUY] ALGO for 0.2978 USDT
`

**Comment by Thornsnake** [comment] 2021-09-28 12:22
The rank of DAI should not matter, because a different coingecko endpoint is used to query stablecoins.
What happened before the bot bought DAI?

Did you recently restart it, or did you manually transfer DAI onto your exchange account?

**Comment by Thornsnake** [comment] 2021-10-15 07:59
Lacking information to reproduce. Will close this issue for now.

**Closed as completed by Thornsnake** 2021-10-15 07:59 UTC
